### ISSUE TITLE
randomly distribute loyalty among "civilians"

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/TvT_Catch_The_Flight.Stratis#37]
that is:

* have INDEP H, OPFOR H slot as civilians
* *after* mission start, give them their loyalty (as task) and set them free
* /probably/ there should be *some* way that OPFOR A / INDEP C can ascertain their loyalty

**Comment by JonasJurczok** [comment]
Maybe after you assign the slots you can show everyone two or three names that they know in their respective organisation.

At least the INDEP C should know his two most loyal supporters and they also have friends in the team. Then every team can establish who is on their side...

And as all are slotted as civilians the name tag above the people does not give anything away and you can still enter vehicles and stuff..

**Comment by Fusselwurm** [comment]
so… I'd have to make sure that everyone's loyalty is known by at least one other person in the same team? :grimacing: interesting problem. I guess every client could, at random pick two other players from the same team, and ping them with "i'm on your side". :+1: … but still I wouldnt necessarily get a single network.… huh. probably something the server should do. like… have it create a tree originating with the INDEP C

**Comment by Fusselwurm** [comment]
prioritized, b/c it could essentially solve #34 and #30

**Comment by Fusselwurm** [comment]
I'd love to introduce the background check:

an action that 
* may be performed once per side per possible allegiance, after which the result is permanently stored and instantly retrievable
* answers the questions "is person aligned with us" and "is person aligned with enemy"
* may be performed by high ranking persons only (usually only one)
* takes about a minute
* may return a boolean value
* will return false positives in 10% of all cases
* will return false negatives in 50% of all cases

**Comment by Fusselwurm** [comment]
getestet und läuft
